name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add Homebrew to PATH
        shell: bash
        run: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Build
        run: | 
          cd iTunes2/scripts
          rake -f Rakefile build
